;-------------------------------------------------------
TEMP 	EQU 03CH
PRESS	EQU IE.5
P_AB	EQU PSW.1
CHANGE	EQU PSW.5

PORT_A EQU 9000H
PORT_B EQU 9001H
PORT_C EQU 9002H
CTRL    EQU 9003H
	ORG 0000H
	
	MOV TEMP,#50
	MOV DPTR,#CTRL
	MOV A,#10001001B
	MOVX @DPTR, A
	CLR PRESS
LOOP:	MOV R2,#00
	SETB CHANGE
PRESS_A:MOV DPTR,#PORT_C
	MOVX A,@DPTR
	ORL A,#11111110B
	CJNE A,#11111110B,PRESS_B
	AJMP JUMP_A
PRESS_B:MOV DPTR,#PORT_C
	MOVX A,@DPTR
	ORL A,#11111101B
	CJNE A,#11111101B,CHANGEPRESS
	AJMP JUMP_B
	
JUMP_A:	CLR P_AB
	SETB PRESS
	MOV DPTR,#PORT_B
	MOV A,#00H
	MOVX @DPTR,A
	AJMP LOOP
JUMP_B: SETB P_AB
	SETB PRESS
	MOV DPTR,#PORT_A
	MOV A,#00H
	MOVX @DPTR,A
	AJMP LOOP

CHANGEPRESS: JB PRESS,CHANGELOOP
	AJMP LOOP
	
CHANGELOOP:CJNE R2,#11111111B,ROTATE
	CPL CHANGE
	MOV R2,#00
	AJMP CHANGEPORT
	
ROTATE:	JB CHANGE,RO_L
RO_R :	MOV A,R2
	RR A
	ORL A,#10000000B
	MOV R2,A
	AJMP CHANGEPORT
RO_L:	MOV A,R2
	RL A
	ORL A,#00000001B
	MOV R2,A
	AJMP CHANGEPORT
	
CHANGEPORT: JB P_AB,PORT_BB
PORT_AA: MOV A,R2
	MOV DPTR,#PORT_A
	MOVX @DPTR,A
	ACALL DELAY
	LJMP PRESS_A
PORT_BB:MOV A,R2
	MOV DPTR,#PORT_B
	MOVX @DPTR,A
	ACALL DELAY
	LJMP PRESS_A
	
DELAY:	MOV	R7, TEMP	; 1 M.Cycle
LOOP1:	MOV	R6,#20	; 1 M.Cycle
LOOP2:	MOV	R5,#80
LOOP3:	DEC	R5		; 1 M.Cycle
	CJNE	R5, #0, LOOP3; 2 M.Cycles
	DEC	R6		; 1 M.Cycle
	CJNE	R6, #0, LOOP2; 2 M.Cycles
	DEC	R7		; 1 M.Cycle
	CJNE	R7, #0, LOOP1; 2 M.Cycles
	RET			; 2 M.Cycles
	END         
